version: '3.4'

services:
  charm.postgresapi:
    image: ${DOCKER_REGISTRY-}charmpostgresapi
    build:
      context: .
      dockerfile: Charm.PostgresApi/Dockerfile
  postgres:
    image: postgres:13.3
    env_file:
      - database.env
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    external: true